# 服务端口的配置
server:
  port: 9899 # 注意端口的设置
  context: /
# 数据库配置
# "root:020913@tcp(127.0.0.1:3306)/kva?charset=utf8&parseTime=True&loc=Local", // DSN data source name
database:
  # mysql 数据库的配置
  mysql:
    host: "127.0.0.1"
    port: "3306"
    dbname: "kva"
    username: "root"
    password: "123456"
    config: "charset=utf8&parseTime=True&loc=Local"
  # nosql 数据库的配置
  nosql:
    redis:
      host: "127.0.0.1:6379"
      port: "3306"
      password: "123"
      db: "0"
    es:
      host: "127.0.0.1"
      port: "9300"
      password: "456"